# Generated by Django 5.0.4 on 2024-05-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artiles',
            new_name='Artilces',
        ),
    ]
