# Generated by Django 5.0.4 on 2024-05-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnews', '0002_rename_artiles_artilces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artilces',
            new_name='Articles',
        ),
    ]
